import 'package:freezed_annotation/freezed_annotation.dart';

part 'chari_components.freezed.dart';
part 'chari_components.g.dart';

@freezed
class ChariComponents with _$ChariComponents {
  const factory ChariComponents({
    required String forkBrand,
    required String forkName,
    required String headsetBrand,
    required String headsetName,
    required String columnspacerBrand,
    required String columnspacerName,
    required String handlebarBrand,
    required String handlebarName,
    required String stemBrand,
    required String stemName,
    required String stemcapBrand,
    required String stemcapName,
    required String gripBrand,
    required String gripName,
    required String bartapeBrand,
    required String bartapeName,
    required String barendBrand,
    required String barendName,
    required String saddleBrand,
    required String saddleName,
    required String seatpostBrand,
    required String seatpostName,
    required String seatclampBrand,
    required String seatclampName,
    required String tireBrand,
    required String tireName,
    required String wheelRimBrand,
    required String wheelRimName,
    required String hubBrand,
    required String hubName,
    required String cogBrand,
    required String cogName,
    required String lockringBrand,
    required String lockringName,
    required String freewheelBrand,
    required String freewheelName,
    required String crankBrand,
    required String crankName,
    required String chainringBrand,
    required String chainringName,
    required String chainBrand,
    required String chainName,
    required String bottombrancketBrand,
    required String bottombrancketName,
    required String pedalsBrand,
    required String pedalsName,
    required String toecripBrand,
    required String toecripName,
    required String toestrapBrand,
    required String toestrapName,
    required String brakeBrand,
    required String brakeName,
    required String brakeleverBrand,
    required String brakeleverName,
    required String brakecableBrand,
    required String brakecableName,
    required String shifterBrand,
    required String shifterName,
    required String frontRackBrand,
    required String frontRackName,
    required String rearRackBrand,
    required String rearRackName,
    required String bottleBrand,
    required String bottleName,
    required String frontLightBrand,
    required String frontLightName,
    required String rearLightBrand,
    required String rearLightName,
    required String lockBrand,
    required String lockName,
    required String bellBrand,
    required String bellName,
    required String helmetBrand,
    required String helmetName,
    required String stemBagBrand,
    required String stemBagName,
    required String handleBagBrand,
    required String handleBagName,
    required String frameBrand,
    required String frameName,
  }) = _ChariComponents;
 factory ChariComponents.fromJson(Map<String, dynamic> json) =>
      _$ChariComponentsFromJson(json);
}
