// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'chari_components.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_ChariComponents _$$_ChariComponentsFromJson(Map<String, dynamic> json) =>
    _$_ChariComponents(
      forkBrand: json['forkBrand'] as String,
      forkName: json['forkName'] as String,
      headsetBrand: json['headsetBrand'] as String,
      headsetName: json['headsetName'] as String,
      columnspacerBrand: json['columnspacerBrand'] as String,
      columnspacerName: json['columnspacerName'] as String,
      handlebarBrand: json['handlebarBrand'] as String,
      handlebarName: json['handlebarName'] as String,
      stemBrand: json['stemBrand'] as String,
      stemName: json['stemName'] as String,
      stemcapBrand: json['stemcapBrand'] as String,
      stemcapName: json['stemcapName'] as String,
      gripBrand: json['gripBrand'] as String,
      gripName: json['gripName'] as String,
      bartapeBrand: json['bartapeBrand'] as String,
      bartapeName: json['bartapeName'] as String,
      barendBrand: json['barendBrand'] as String,
      barendName: json['barendName'] as String,
      saddleBrand: json['saddleBrand'] as String,
      saddleName: json['saddleName'] as String,
      seatpostBrand: json['seatpostBrand'] as String,
      seatpostName: json['seatpostName'] as String,
      seatclampBrand: json['seatclampBrand'] as String,
      seatclampName: json['seatclampName'] as String,
      tireBrand: json['tireBrand'] as String,
      tireName: json['tireName'] as String,
      wheelRimBrand: json['wheelRimBrand'] as String,
      wheelRimName: json['wheelRimName'] as String,
      hubBrand: json['hubBrand'] as String,
      hubName: json['hubName'] as String,
      cogBrand: json['cogBrand'] as String,
      cogName: json['cogName'] as String,
      lockringBrand: json['lockringBrand'] as String,
      lockringName: json['lockringName'] as String,
      freewheelBrand: json['freewheelBrand'] as String,
      freewheelName: json['freewheelName'] as String,
      crankBrand: json['crankBrand'] as String,
      crankName: json['crankName'] as String,
      chainringBrand: json['chainringBrand'] as String,
      chainringName: json['chainringName'] as String,
      chainBrand: json['chainBrand'] as String,
      chainName: json['chainName'] as String,
      bottombrancketBrand: json['bottombrancketBrand'] as String,
      bottombrancketName: json['bottombrancketName'] as String,
      pedalsBrand: json['pedalsBrand'] as String,
      pedalsName: json['pedalsName'] as String,
      toecripBrand: json['toecripBrand'] as String,
      toecripName: json['toecripName'] as String,
      toestrapBrand: json['toestrapBrand'] as String,
      toestrapName: json['toestrapName'] as String,
      brakeBrand: json['brakeBrand'] as String,
      brakeName: json['brakeName'] as String,
      brakeleverBrand: json['brakeleverBrand'] as String,
      brakeleverName: json['brakeleverName'] as String,
      brakecableBrand: json['brakecableBrand'] as String,
      brakecableName: json['brakecableName'] as String,
      shifterBrand: json['shifterBrand'] as String,
      shifterName: json['shifterName'] as String,
      frontRackBrand: json['frontRackBrand'] as String,
      frontRackName: json['frontRackName'] as String,
      rearRackBrand: json['rearRackBrand'] as String,
      rearRackName: json['rearRackName'] as String,
      bottleBrand: json['bottleBrand'] as String,
      bottleName: json['bottleName'] as String,
      frontLightBrand: json['frontLightBrand'] as String,
      frontLightName: json['frontLightName'] as String,
      rearLightBrand: json['rearLightBrand'] as String,
      rearLightName: json['rearLightName'] as String,
      lockBrand: json['lockBrand'] as String,
      lockName: json['lockName'] as String,
      bellBrand: json['bellBrand'] as String,
      bellName: json['bellName'] as String,
      helmetBrand: json['helmetBrand'] as String,
      helmetName: json['helmetName'] as String,
      stemBagBrand: json['stemBagBrand'] as String,
      stemBagName: json['stemBagName'] as String,
      handleBagBrand: json['handleBagBrand'] as String,
      handleBagName: json['handleBagName'] as String,
      frameBrand: json['frameBrand'] as String,
      frameName: json['frameName'] as String,
    );

Map<String, dynamic> _$$_ChariComponentsToJson(_$_ChariComponents instance) =>
    <String, dynamic>{
      'forkBrand': instance.forkBrand,
      'forkName': instance.forkName,
      'headsetBrand': instance.headsetBrand,
      'headsetName': instance.headsetName,
      'columnspacerBrand': instance.columnspacerBrand,
      'columnspacerName': instance.columnspacerName,
      'handlebarBrand': instance.handlebarBrand,
      'handlebarName': instance.handlebarName,
      'stemBrand': instance.stemBrand,
      'stemName': instance.stemName,
      'stemcapBrand': instance.stemcapBrand,
      'stemcapName': instance.stemcapName,
      'gripBrand': instance.gripBrand,
      'gripName': instance.gripName,
      'bartapeBrand': instance.bartapeBrand,
      'bartapeName': instance.bartapeName,
      'barendBrand': instance.barendBrand,
      'barendName': instance.barendName,
      'saddleBrand': instance.saddleBrand,
      'saddleName': instance.saddleName,
      'seatpostBrand': instance.seatpostBrand,
      'seatpostName': instance.seatpostName,
      'seatclampBrand': instance.seatclampBrand,
      'seatclampName': instance.seatclampName,
      'tireBrand': instance.tireBrand,
      'tireName': instance.tireName,
      'wheelRimBrand': instance.wheelRimBrand,
      'wheelRimName': instance.wheelRimName,
      'hubBrand': instance.hubBrand,
      'hubName': instance.hubName,
      'cogBrand': instance.cogBrand,
      'cogName': instance.cogName,
      'lockringBrand': instance.lockringBrand,
      'lockringName': instance.lockringName,
      'freewheelBrand': instance.freewheelBrand,
      'freewheelName': instance.freewheelName,
      'crankBrand': instance.crankBrand,
      'crankName': instance.crankName,
      'chainringBrand': instance.chainringBrand,
      'chainringName': instance.chainringName,
      'chainBrand': instance.chainBrand,
      'chainName': instance.chainName,
      'bottombrancketBrand': instance.bottombrancketBrand,
      'bottombrancketName': instance.bottombrancketName,
      'pedalsBrand': instance.pedalsBrand,
      'pedalsName': instance.pedalsName,
      'toecripBrand': instance.toecripBrand,
      'toecripName': instance.toecripName,
      'toestrapBrand': instance.toestrapBrand,
      'toestrapName': instance.toestrapName,
      'brakeBrand': instance.brakeBrand,
      'brakeName': instance.brakeName,
      'brakeleverBrand': instance.brakeleverBrand,
      'brakeleverName': instance.brakeleverName,
      'brakecableBrand': instance.brakecableBrand,
      'brakecableName': instance.brakecableName,
      'shifterBrand': instance.shifterBrand,
      'shifterName': instance.shifterName,
      'frontRackBrand': instance.frontRackBrand,
      'frontRackName': instance.frontRackName,
      'rearRackBrand': instance.rearRackBrand,
      'rearRackName': instance.rearRackName,
      'bottleBrand': instance.bottleBrand,
      'bottleName': instance.bottleName,
      'frontLightBrand': instance.frontLightBrand,
      'frontLightName': instance.frontLightName,
      'rearLightBrand': instance.rearLightBrand,
      'rearLightName': instance.rearLightName,
      'lockBrand': instance.lockBrand,
      'lockName': instance.lockName,
      'bellBrand': instance.bellBrand,
      'bellName': instance.bellName,
      'helmetBrand': instance.helmetBrand,
      'helmetName': instance.helmetName,
      'stemBagBrand': instance.stemBagBrand,
      'stemBagName': instance.stemBagName,
      'handleBagBrand': instance.handleBagBrand,
      'handleBagName': instance.handleBagName,
      'frameBrand': instance.frameBrand,
      'frameName': instance.frameName,
    };
