name: yourchari_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.2
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1
  cloud_firestore: ^4.5.1
  firebase_analytics: ^10.2.0
  google_fonts: ^4.0.3
  pull_to_refresh: ^2.0.0
  image_cropper: ^1.4.1
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  clipboard: ^0.1.3
  flutter_launcher_icons: ^0.13.0
  flash: ^2.0.3+1
  uuid: ^3.0.5
  image_picker: ^0.8.7+4
  flutter_svg: ^2.0.5
  firebase_storage: ^11.1.1
  firebase_crashlytics: ^3.1.0
  fluttertoast: ^8.0.9
  material_floating_search_bar: ^0.3.7
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  algolia: ^1.1.1
  freezed: ^2.3.2
  tuple: ^2.0.1
  carousel_slider: ^4.2.1
  freezed_annotation: ^2.2.0
  persistent_bottom_nav_bar: ^5.0.2
  flutter_image_compress: ^2.0.3
  cached_network_image: ^3.2.3
  timeago: ^3.4.0
  sticky_headers: ^0.3.0+2
  another_flushbar: ^1.12.30

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  
  uses-material-design: true

  # 画像を参照
  assets:
    - assets/
    - assets/images/
  



