// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'chari.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$_Chari _$$_ChariFromJson(Map<String, dynamic> json) => _$_Chari(
      brand: json['brand'] as String,
      category: json['category'] as String,
      frame: json['frame'] as String,
      imageURL:
          (json['imageURL'] as List<dynamic>).map((e) => e as String).toList(),
      likeCount: json['likeCount'] as int,
      postId: json['postId'] as String,
      uid: json['uid'] as String,
      caption: json['caption'] as String,
      createdAt: json['createdAt'],
      updatedAt: json['updatedAt'],
      fork: json['fork'] as Map<String, dynamic>?,
      headSet: json['headSet'] as Map<String, dynamic>?,
      columnSpacer: json['columnSpacer'] as Map<String, dynamic>?,
      handleBar: json['handleBar'] as Map<String, dynamic>?,
      stem: json['stem'] as Map<String, dynamic>?,
      grip: json['grip'] as Map<String, dynamic>?,
      saddle: json['saddle'] as Map<String, dynamic>?,
      seatPost: json['seatPost'] as Map<String, dynamic>?,
      seatClamp: json['seatClamp'] as Map<String, dynamic>?,
      tire: json['tire'] as Map<String, dynamic>?,
      rim: json['rim'] as Map<String, dynamic>?,
      hub: json['hub'] as Map<String, dynamic>?,
      cog: json['cog'] as Map<String, dynamic>?,
      sprocket: json['sprocket'] as Map<String, dynamic>?,
      lockRing: json['lockRing'] as Map<String, dynamic>?,
      freeWheel: json['freeWheel'] as Map<String, dynamic>?,
      crank: json['crank'] as Map<String, dynamic>?,
      charinRing: json['charinRing'] as Map<String, dynamic>?,
      chain: json['chain'] as Map<String, dynamic>?,
      bottomBrancket: json['bottomBrancket'] as Map<String, dynamic>?,
      pedals: json['pedals'] as Map<String, dynamic>?,
      brake: json['brake'] as Map<String, dynamic>?,
      brakeLever: json['brakeLever'] as Map<String, dynamic>?,
      shifter: json['shifter'] as Map<String, dynamic>?,
      shiftLever: json['shiftLever'] as Map<String, dynamic>?,
      rack: json['rack'] as Map<String, dynamic>?,
      bottle: json['bottle'] as Map<String, dynamic>?,
      frontLight: json['frontLight'] as Map<String, dynamic>?,
      rearLight: json['rearLight'] as Map<String, dynamic>?,
      lock: json['lock'] as Map<String, dynamic>?,
      bell: json['bell'] as Map<String, dynamic>?,
      helmet: json['helmet'] as Map<String, dynamic>?,
      bag: json['bag'] as Map<String, dynamic>?,
      baske: json['baske'] as Map<String, dynamic>?,
    );

Map<String, dynamic> _$$_ChariToJson(_$_Chari instance) => <String, dynamic>{
      'brand': instance.brand,
      'category': instance.category,
      'frame': instance.frame,
      'imageURL': instance.imageURL,
      'likeCount': instance.likeCount,
      'postId': instance.postId,
      'uid': instance.uid,
      'caption': instance.caption,
      'createdAt': instance.createdAt,
      'updatedAt': instance.updatedAt,
      'fork': instance.fork,
      'headSet': instance.headSet,
      'columnSpacer': instance.columnSpacer,
      'handleBar': instance.handleBar,
      'stem': instance.stem,
      'grip': instance.grip,
      'saddle': instance.saddle,
      'seatPost': instance.seatPost,
      'seatClamp': instance.seatClamp,
      'tire': instance.tire,
      'rim': instance.rim,
      'hub': instance.hub,
      'cog': instance.cog,
      'sprocket': instance.sprocket,
      'lockRing': instance.lockRing,
      'freeWheel': instance.freeWheel,
      'crank': instance.crank,
      'charinRing': instance.charinRing,
      'chain': instance.chain,
      'bottomBrancket': instance.bottomBrancket,
      'pedals': instance.pedals,
      'brake': instance.brake,
      'brakeLever': instance.brakeLever,
      'shifter': instance.shifter,
      'shiftLever': instance.shiftLever,
      'rack': instance.rack,
      'bottle': instance.bottle,
      'frontLight': instance.frontLight,
      'rearLight': instance.rearLight,
      'lock': instance.lock,
      'bell': instance.bell,
      'helmet': instance.helmet,
      'bag': instance.bag,
      'baske': instance.baske,
    };
