// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD99b33NCEiKS6VpUKDRExIe-TlAvDnL0U',
    appId: '1:644207087062:web:887ad0a6066a9aafe76877',
    messagingSenderId: '644207087062',
    projectId: 'y-chari',
    authDomain: 'y-chari.firebaseapp.com',
    storageBucket: 'y-chari.appspot.com',
    measurementId: 'G-ZNBZSV90YV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHKqKOMHiFY-PphOnUKprbwRWKPJEq9dM',
    appId: '1:644207087062:android:bbb81538de0e0516e76877',
    messagingSenderId: '644207087062',
    projectId: 'y-chari',
    storageBucket: 'y-chari.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIJSCeVzuCGFoW16HSdD0PdnvwvBoWQPI',
    appId: '1:644207087062:ios:ca4f3bb7a415205ee76877',
    messagingSenderId: '644207087062',
    projectId: 'y-chari',
    storageBucket: 'y-chari.appspot.com',
    iosClientId: '644207087062-v2d7acfa0uegjeg6pboqqt1unk3fjqe1.apps.googleusercontent.com',
    iosBundleId: 'app.yourchari.YourChariApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIJSCeVzuCGFoW16HSdD0PdnvwvBoWQPI',
    appId: '1:644207087062:ios:ca4f3bb7a415205ee76877',
    messagingSenderId: '644207087062',
    projectId: 'y-chari',
    storageBucket: 'y-chari.appspot.com',
    iosClientId: '644207087062-v2d7acfa0uegjeg6pboqqt1unk3fjqe1.apps.googleusercontent.com',
    iosBundleId: 'app.yourchari.YourChariApp',
  );
}
